# Generated by Django 4.1.6 on 2023-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thoughtsModel',
            fields=[
                ('username', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
